aws_account: "637423635181"
aws_region: us-east-1

vpc:
  name: vpc-dev
  cidr: 10.24.0.0/16
  maxAzs: 2
  natGateways: 1
  subnets:
    public:
      name: Public
      cidr: 24
    private:
      name: Private
      cidr: 20
    db:
      name: DB
      cidr: 24

eks:
  clusterName: ms-eks-dev
  version: "1.30"
  NodeGroup:
    instanceTypes:
      - "t3.medium"
      - "t3.large"
    minCapacity: 2
    maxCapacity: 5
    desiredCapacity: 3
    diskSize: 20
    capacityType: ON_DEMAND
  adminAccess:
    roleArnPrefix: "yourSSORole"
  addOns:
    - name: coredns
      version: v1.11.3-eksbuild.1
    - name: vpc-cni
      version: v1.18.3-eksbuild.3
    - name: kube-proxy
      version: v1.30.3-eksbuild.5
    - name: eks-pod-identity-agent
      version: v1.3.2-eksbuild.2
    # - name: kubecost_kubecost
    #   version: v1.96.0-eksbuild.1
  awsLoadBalancerController:
    namespace: kube-system
    serviceAccountName: aws-load-balancer-controller
    version: 1.5.3
  ebsCsiDriver:
    namespace: kube-system
    serviceAccountName: ebs-csi-controller-sa
    version: 2.20.0
  metricsServer:
    version: "3.12.1"
    namespace: kube-system

rds:
  auroraEngineVersion: "8.0.mysql_aurora.3.05.2"
  instanceName: myRDS
  writerInstanceClass: T3
  writerInstanceSize: MEDIUM
  writerAllowMajorVersionUpgrade: false 
  writerAutoMinorVersionUpgrade: true
  readersInstanceClass: T3
  readersInstanceSize: MEDIUM
  readersAllowMajorVersionUpgrade: false
  readersAutoMinorVersionUpgrade: true
  readersInstanceCount: 0
  databasePrefix: db
  allocatedStorage: 20
  maxAllocatedStorage: 100
  removalPolicy: DESTROY
  deletionProtection: false
  backupRetentionDays: 7
  backupPreferredWindow: "03:00-04:00"
  databaseName: mydb 
  storageEncrypted: true

nlb:
  internal:
    name: jcroyoaun-nlb-int-dev
    scheme: internal
    subnetType: PRIVATE_WITH_EGRESS
  external:
    name: jcroyoaun-nlb-ext-dev
    scheme: internet-facing
    subnetType: PUBLIC
  common:
    type: network
    ipAddressType: ipv4