aws_account: "637423635181"
aws_region: us-east-1

vpc:
  name: dev-vpc
  cidr: 10.24.0.0/16
  maxAzs: 2
  natGateways: 1
  subnets:
    public:
      name: Public
      cidr: 24
    private:
      name: Private
      cidr: 20
    db:
      name: Database
      cidr: 24

eks:
  clusterName: ms-eks-develop
  version: "1.30"
  NodeGroup:
    instanceTypes:
      - "t3.medium"
      - "t3.large"
    minCapacity: 2
    maxCapacity: 5
    desiredCapacity: 3
    diskSize: 20
    capacityType: ON_DEMAND
  adminAccess:
    roleArnPrefix: "arn:aws:iam::637423635181:role/AWSReservedSSO_AWSAdministratorAccess"
  addOns:
    - name: coredns
      version: v1.9.3-eksbuild.3
    - name: vpc-cni
      version: v1.12.6-eksbuild.1
    - name: kube-proxy
      version: v1.26.2-eksbuild.1
    - name: eks-pod-identity-agent
      version: v1.0.0-eksbuild.1
    - name: kubecost_kubecost
      version: v1.96.0-eksbuild.1
  awsLoadBalancerController:
    namespace: kube-system
    serviceAccountName: aws-load-balancer-controller
    version: 1.5.3
  ebsCsiDriver:
    namespace: kube-system
    serviceAccountName: ebs-csi-controller-sa
    version: 2.20.0

rds:
  auroraEngineVersion: "8.0.mysql_aurora.3.05.2"
  instanceName: drupalRDS
  writerInstanceClass: T3
  writerInstanceSize: MEDIUM
  writerAllowMajorVersionUpgrade: true
  writerAutoMinorVersionUpgrade: true
  readersInstanceClass: T3
  readersInstanceSize: MEDIUM
  readersAllowMajorVersionUpgrade: true
  readersAutoMinorVersionUpgrade: true
  readersInstanceCount: 0
  databasePrefix: develop
  allocatedStorage: 20
  maxAllocatedStorage: 100
  removalPolicy: DESTROY
  deletionProtection: false
  backupRetentionDays: 7
  backupPreferredWindow: "03:00-04:00"
  databaseName: drupal
  storageEncrypted: true